--- Dockerfile	2024-04-05 12:46:10.517527091 -0400
+++ ../fsu-xform-isle-apache/Dockerfile	2024-04-05 12:47:17.660834002 -0400
@@ -1,5 +1,5 @@
 # @see https://github.com/adoptium/containers/blob/main/8/jdk/ubuntu/focal/Dockerfile.releases.full for newer supported java updates
-FROM eclipse-temurin:8-jdk-focal
+FROM 840783682283.dkr.ecr.us-east-1.amazonaws.com/eclipse-temurin/eclipse-temurin:8-jdk-focal
 
 ENV INITRD=no \
     ISLANDORA_UID=${ISLANDORA_UID:-1000} \
@@ -28,7 +28,8 @@
     openssl \
     openssh-client \
     mysql-client\
-    file" && \
+    file \ 
+    rsyslog" && \
     echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
     apt-get update && \
     apt-get install --no-install-recommends -y $GEN_DEP_PACKS && \
@@ -232,6 +233,8 @@
 # @see: Drush https://github.com/drush-ops/drush/tags
 RUN useradd --comment 'Islandora User' --no-create-home -d /var/www/html --system --uid $ISLANDORA_UID --user-group -s /bin/bash islandora && \
     chown -R islandora:www-data /var/www/html && \
+    ## FSULIB: rsyslog.conf tweak
+    sed -i -e '25s/^/#/' -e '43s/syslog/islandora/' -e '48s/syslog/islandora/' /etc/rsyslog.conf && \
     ## Temporary directory for composer, fits, etc...
     mkdir -p /tmp/build && \
     cd /tmp/build/ && \
